# https://docs.docker.com/compose/compose-file/
version: "3.3"

services:
  dhcp-stats-prometheus:
    container_name: dhcp-stats-prometheus
    build: ./
    image: dhcp-stats-prometheus
    tty: true
    hostname: dhcp-stats-prometheus
    volumes:
        - /etc/dhcpd/:/etc/dhcpd:ro
        - /var/lib/dhcpd/dhcpd.leases:/var/lib/dhcpd/dhcpd.leases:ro
    ports:
        - 12776:12776
    restart: always